### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Fevix** [GLotsapot/HellionSaveEditor#11]
After following the instructions in the wiki (Locate .save files, create folder, add the exe and the dll to new folder, run exe from in folder) the program opens a command prompt window and closes. I managed to get a screenshot of the error: 
![Error](https://gyazo.com/0dd09b42cd163b3da59b34d110412597.png)

**Comment by GLotsapot** [comment]
You're missing the file "HellionData.dll" that is included in the same folder as "HellionSaveEditor.exe".

**Comment by Fevix** [comment]
This file is not mentioned in the installation instructions found at https://github.com/GLotsapot/HellionSaveEditor/wiki

The installation instructions ONLY say to copy the .exe and the NewtonSoft.Json.dll files

**Comment by GLotsapot** [comment]
Apologies, I thought I had updated the wiki after release 2.0 - I have done so now
